version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    ports:
      - 80:3000
      - 9229:9229
    environment:
      MONGO_URI: mongodb://mongo/matchit
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start"

volumes:
  mongo-data:
