name: Deploy to production
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key.pem
          chmod 400 /tmp/ssh-key.pem
          mkdir ~/.ssh/
          echo ec2-18-197-40-148.eu-central-1.compute.amazonaws.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHGKoxeOaUBycQ8dkY3SlW8TQboEg6uWdbF1q9P0onvxC4JE7PQdYkkHn3uES0E2CPsW0hfdvzTYxVb0p7iEpHA= > ~/.ssh/known_hosts
      - name: Deploy code
        run: ./ci/deploy.sh
