name: Deploy to production
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > /tmp/ssh-key.pem
          chmod 400 /tmp/ssh-key.pem
      - name: Deploy code
        run: ./ci/deploy.sh
